# Generated by Django 4.2.7 on 2026-03-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('home_tech_type', models.CharField(max_length=100, verbose_name='Тип техники')),
                ('home_tech_model', models.CharField(max_length=100, verbose_name='Модель техники')),
                ('problem_description', models.TextField(verbose_name='Описание проблемы')),
                ('request_status', models.BooleanField(default=False, verbose_name='Статус (выполнено/нет)')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('repair_parts', models.TextField(blank=True, verbose_name='Запчасти')),
                ('client', models.ForeignKey(db_column='clientID', on_delete=django.db.models.deletion.CASCADE, to='accounts.client', verbose_name='Клиент')),
                ('master', models.ForeignKey(db_column='masterID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('master', models.ForeignKey(db_column='masterID', on_delete=django.db.models.deletion.CASCADE, to='accounts.master', verbose_name='Мастер')),
                ('request', models.ForeignKey(db_column='requestID', on_delete=django.db.models.deletion.CASCADE, to='requests1.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comments',
            },
        ),
    ]
