# Generated by Django 4.2.7 on 2026-04-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_user_role'),
        ('requests1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='master',
            field=models.ForeignKey(blank=True, db_column='masterID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('new', 'Новая'), ('pending', 'Ожидает'), ('in_progress', 'В процессе ремонта'), ('ready', 'Готово'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
