# Generated by Django 4.2.7 on 2026-04-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
                ('can_create_tickets', models.BooleanField(default=False, verbose_name='Создание заявок')),
                ('can_view_all_tickets', models.BooleanField(default=False, verbose_name='Просмотр всех заявок')),
                ('can_change_ticket_status', models.BooleanField(default=False, verbose_name='Изменение статуса')),
                ('can_assign_master', models.BooleanField(default=False, verbose_name='Назначение мастера')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Управление пользователями')),
                ('can_manage_roles', models.BooleanField(default=False, verbose_name='Управление ролями')),
                ('can_view_stats', models.BooleanField(default=False, verbose_name='Просмотр статистики')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, db_column='roleID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role', verbose_name='Роль'),
        ),
    ]
